### PR TITLE
Fix compile error on python > 3.2

### PR DESCRIPTION
**Pull request by Ph0rk0z**
I couldn't compile the uefipayloadpkg because of a python error. Phython has replaced tostring with tobytes and the fromXXX as well since version 3.2

I was then able to build. Bios still runs

### CODE REVIEW

**Comment by MrChromebox** [comment]
I'm not going to change things with upstream edk2 that will break existing setups that work with python2 as the default. would be better to override the buildtools somehow to force use of python2

**Comment by Ph0rk0z** [comment]
Whichever way works. At least the problem is documented. I thought I saw this in the coreboot branch too but that builds fine.

**Comment by benjamindoron** [comment]
Also see https://github.com/benjamindoron/edk2_coreboot-dev/commit/0209199dfce2f31033d02212866d6aa9429e093c, which I found on the mailing list (https://edk2.groups.io/g/devel/message/66174). A fix for this issue in "GenFds" was recently committed upstream (https://github.com/tianocore/edk2/commit/20b292d0cdf7dce58d824fdf9ab1613c2a1ad2ec), but not for "Eot."

**Comment by MrChromebox** [comment]
ugh, mailing list patches, lol. I'll pull them in

**Comment by MrChromebox** [comment]
ok, pushed. LMK if that fixes the issue

**Comment by ismell** [comment]
Does upstream EDK2 support python 3.2?

**Pull request closed without merging**
