### PR TITLE
Feature additions

### PR DESCRIPTION
**Pull request by benjamindoron**
Adds Secure Boot, TPM and networking support, as well as some additional filesystem drivers. Also adds RNG and EFI Byte Code support.

I will check with Patrick whether I can use SecureBootEnrollDefaultKeys, but Secure Boot can be enabled without it.

### CODE REVIEW

**Comment by MrChromebox** [comment]
I'll try to test these this weekend, will probably pull/test one at a time since it's a pretty big list

**Review by MrChromebox — COMMENTED** [review]
for 3d1aa5f, I'll likely go back and amend the others to include these bits.

for f3dd1b8, not sure I like the look of the progress bar.

for 2704212, what qemu args did you use to test?

**Comment by benjamindoron** [comment]
https://github.com/MrChromebox/edk2/commit/f3dd1b85e5b035c4bd46caa7781de9e3afc49ff8: The intention was to make `BootLogoUpdateProgress` do what the function comment describes. This is how the function is used in OVMF, as well as the Raspberry Pi in edk2-platforms.

https://github.com/MrChromebox/edk2/commit/27042121aabc3fc695db38cf8d99c5dc39ec8c3b
QEMU Q35 machine used, built with relevant TPM version support.

TPM1.2:
SwTPM: `swtpm socket --tpmstate dir=/dev/shm/tpm12 --ctrl type=unixio,path=/dev/shm/tpm12/swtpm-sock --log level=20`
QEMU: `qemu-system-x86_64 -M q35 -bios build/coreboot.rom -serial stdio -chardev socket,id=chrtpm,path=/dev/shm/tpm12/swtpm-sock -tpmdev emulator,id=tpm0,chardev=chrtpm -device tpm-tis,tpmdev=tpm0`

TPM2:
SwTPM: `swtpm socket --tpmstate dir=/dev/shm/tpm20 --tpm2 --ctrl type=unixio,path=/dev/shm/tpm20/swtpm-sock --log level=20`
QEMU: `qemu-system-x86_64 -M q35 -bios build/coreboot.rom -serial stdio -chardev socket,id=chrtpm,path=/dev/shm/tpm20/swtpm-sock -tpmdev emulator,id=tpm0,chardev=chrtpm -device tpm-tis,tpmdev=tpm0`

**Comment by MrChromebox** [comment]
> [f3dd1b8](https://github.com/MrChromebox/edk2/commit/f3dd1b85e5b035c4bd46caa7781de9e3afc49ff8): The intention was to make `BootLogoUpdateProgress` do what the function comment describes. This is how the function is used in OVMF, as well as the Raspberry Pi in edk2-platforms.

yeah, I get that, just not a fan of how it looks

**Comment by benjamindoron** [comment]
> > [f3dd1b8](https://github.com/MrChromebox/edk2/commit/f3dd1b85e5b035c4bd46caa7781de9e3afc49ff8): The intention was to make `BootLogoUpdateProgress` do what the function comment describes. This is how the function is used in OVMF, as well as the Raspberry Pi in edk2-platforms.
> 
> yeah, I get that, just not a fan of how it looks

Oh, okay. Not a problem, I don't mind dropping that commit.

Also, PTT works (measurements are made into PCRs 0, 7 and 10, only 10 is by IMA) if initialisation and the self-test are skipped in TianoCore (I'm not certain yet if both are necessary), so I'll push updates soon. Assuming that coreboot is normally responsible for bring-up, these don't need to be conditional on PTT.

**Comment by MrChromebox** [comment]
I tested the PR as-is (testing branch), but TPM not working (at least to Windows' satisfaction) on actual hardware (google/wolf, TPM 1.2) when passing `-DTPM_ENABLE -DTPM_CONFIG_ENABLE` in via Tianocore makefile

**Comment by MrChromebox** [comment]
what does EBC support practically provide? I see it's used in Ovmf, but that's about it

**Comment by benjamindoron** [comment]
> what does EBC support practically provide? I see it's used in Ovmf, but that's about it

There are a few EBC applications around (a quick search finds [this](https://firmwaresecurity.com/tag/ebc/)), so I suppose it's slowly gaining adoption. I figured it was a nice-to-have, but I wouldn't be using it myself. Same with networking.

**Comment by benjamindoron** [comment]
Changes:
- DeviceManagerUiLib is required for Secure Boot; inclusion moved to that commit.
- https://github.com/MrChromebox/edk2/commit/f3dd1b85e5b035c4bd46caa7781de9e3afc49ff8 (UefiPayloadPkg: Boot prompt as callback) dropped.
- Fixes for TPM.

**Comment by MrChromebox** [comment]
with 11c7088c, the TPM menu items now appear under Device Manager (whose addition should be kept as part of the TPM commit IMO, and moved below BootManager/BootMaintenanceManager just for menu ordering), but the TPM functions don't appear to change the TPM state (ie, selecting 'Deactivate and Disable' does not result in the state changing upon reboot) and Windows still can't use the TPM properly for Bitlocker

**Comment by benjamindoron** [comment]
Regarding https://github.com/MrChromebox/edk2/pull/9/commits/e66826a9869110e39a93c0d49f7cd934be03f2a3: Whether Secure Boot works or not seems to actually depend on variable support.

On QEMU, with no SMMStore, Secure Boot seems to work. From memory, without https://review.coreboot.org/c/coreboot/+/40520/2 applied to coreboot, Secure Boot works on my Skylake laptop. (However, it becomes impossible to reflash in the OS, due to kernel lockdown. And Secure Boot then cannot be disabled, because there's no variable support.)

To that end (possibly, it wasn't working at all for me, but maybe I mis-applied the patches), have you seen https://review.coreboot.org/c/coreboot/+/40520/7, https://github.com/9elements/edk2-1/commit/99e5608b14d52a3354bd441ee8d14194e9f77b09 and https://github.com/9elements/edk2-1/commit/4d465bad6282ddded4ca791fdd8a27fa8db4672e?

**Comment by benjamindoron** [comment]
> but the TPM functions don't appear to change the TPM state

Maybe that's "Physical Presence" related?

Also, it's inconsistent, but UiApp sometimes fails to open. Not on QEMU though, so it could also be SMM related.

**Comment by MrChromebox** [comment]
I'm using patchset #2 of CB:40520 and the matching Tiano commit (see my coreboot/working and tiano/testing branches), and NVRAM is working properly. I've not updated to the current patchset since it seemed in flux still

**Comment by MrChromebox** [comment]
> Maybe that's "Physical Presence" related?

possibly, I don't have debug output on this machine, I'd need to test on one with a servo interface or CR50 to see what's going on

edit: added the TPM 1.2 PP libs, no change

**Comment by benjamindoron** [comment]
> edit: added the TPM 1.2 PP libs, no change

I believe the library must be called in PlatformBootManager. See https://github.com/tianocore/edk2/commit/8d65d3b25e35a2e968395d261b34416776b95d9e (which probably needs to be adapted for TPM1.2).

I can add that patch (and implicitly, https://github.com/tianocore/edk2/commit/fe280ecbee11f91408eaac40efc1e18729518478), but the SwTPM package may not be enough to test this one.

**Comment by benjamindoron** [comment]
> I can add that patch (and implicitly, tianocore@fe280ec), but the SwTPM package may not be enough to test this one.

It asserts on QEMU when attempting to lock the "PhysicalPresenceFlags" variable with access denied.

Edit: `Tcg*PhysicalPresenceLibProcessRequest` needs to be called in `PlatformBootManagerBeforeConsole` because `VariableLockRequestToLock` can't be called after End-of-DXE or ready-to-boot is signalled. OVMF has their own library to process the request that doesn't use `VariableLockRequestToLock`.

**Comment by macromorgan** [comment]
I'd love to see Secure Boot and TPM support added, is there anything I can do to help test?

**Comment by MrChromebox** [comment]
@macromorgan 9elements is working on those in their fork, but I believe only for TPM 2.0 devices. I need to check in with them and see how it's going.

**Comment by benjamindoron** [comment]
Regarding the differences between the Secure Boot and TPM patches: They're largely the same. 9elements seems to have completed work on theirs as it's no longer marked "WIP." Theirs is also not attempting to handle TCG PP.

I'm not sure that Secure Boot is working. I've tried 9elements' fork as well, but it wouldn't boot any image or allow Secure Boot to be disabled (edit: I forgot to patch SMMStore to use a different CB_TAG; I might try again).

In the TPM patch, UiApp is presently broken, I suspect due to SMMStore. This is because:
1. With TPM enabled, measurement handlers are linked into the security stub, which intercepts LoadImage calls and uses the FVB protocol. Without debug output, I cannot see much more.
2. On QEMU, where SMMStore isn't running, no issues are observed. This is inconvenient for debugging.

Edit: I need to try https://github.com/tianocore/edk2/commit/1755932f89e0b32fa09232661a5ae6c357f4e471 along with its implicit dependencies. I'm also not certain that SMMStore is at fault, as UiApp is not in the SMMStore FV.

Also regarding TPM: Don't attempt to enable SHA256 on Intel PTT, it seems to brick the system. That may be fixed by the recent pushes (or if it's Intel ME-related, any recent update), but I haven't tested it yet. Mostly due to the above.

Other than that, it's all rather straightforward?

**Comment by benjamindoron** [comment]
*ping*
I believe I may have TPM support working on my other branch, https://github.com/benjamindoron/edk2_coreboot-dev/tree/upp_next. For a while, I had the TPM working correctly on the first boot (measurements to PCRs 0-10 and an event log, not just PCRs 0, 7 and 10 as before), but it stopped measuring on successive boots - only to those three PCRs.

For what it's worth, I have an Intel PTT (TPM 2.0 PTP CRB).
It appears there is some delay in bringing the TPM up from idle, but it's difficult to be certain without debug logs. If I enter the "TCG2 configuration" menu, it says that the manufacturer is unknown, or something along those lines, but if I exit and re-enter the menu, it prints "INTC3031" - an Intel PTT. Measurement works afterwards and an event log is generated. So far, this seems reproducible; I've done it twice. I still need to check on this build that the TPM doesn't work without this.

@macromorgan If you can, please do! See my other branch, and enable "TPM_ENABLE" and/or "SECURE_BOOT_ENABLE" in UefiPayloadPkg/UefiPayloadPkg(arch).dsc. Regarding Secure Boot, revert https://github.com/benjamindoron/edk2_coreboot-dev/commit/7ce243f1695a53d1a292c1ef541e45853a51fd8d ([WIP] UefiPayloadPkg: SMMStore VariableStore supports Authenticated V…) if you want - I haven't tested adding certificates at run time. Let me know if you have any questions.

**Comment by MrChromebox** [comment]
still tracking this, just have zero time ATM to try and integrate into my uefipayloadpkg branch, and would ideally like to have something that works for TPM 1.2, PTT/2.0, and CR50 2.0 before I do

**Comment by macromorgan** [comment]
Any restrictions I should know about before I test?  I have a T420/Ivybridge (with a TPM 1.3), a Dell Tricky (think it's a TPM 2.0?), and an Intel Minnow Max 3 (unofficially supported, as a fTPM as near as I can tell).  Think I'll do the Tricky first as it's the easiest to test with a real TPM.  Dread having to reflash the T420 if I soft brick it.

**Comment by MrChromebox** [comment]
> I have a T420/Ivybridge (with a TPM 1.3), a Dell Tricky (think it's a TPM 2.0?),

those are both TPM 1.2. All ChromeOS devices without a CR50 are TPM 1.2; all with one are TPM 2.0

**Comment by benjamindoron** [comment]
> Any restrictions I should know about before I test?

Source-level debug builds seem broken, but that probably doesn't matter (I may have found the issue, but I haven't tested or pushed patches yet).
Other than that, SMMStoreV2 is used, but it's been working fine everywhere it's been tested and coreboot should automatically select it? Also, this is on my other branch, so you'd have to specify when cloning.

>  Dread having to reflash the T420 if I soft brick it.

coreboot's CMOS "fallback" mechanism may help there. (https://www.coreboot.org/Fallback_mechanism)

> All ChromeOS devices without a CR50 are TPM 1.2

Thanks. I think the Minnow Max's fTPM is TPM 2.0

**Comment by macromorgan** [comment]
Tested  https://github.com/benjamindoron/edk2_coreboot-dev/tree/upp_next and the TPM (1.2) isn't working on my Dell Tricky.  I see the options in the setup screen but can't seem to take ownership or clear the TPM (either via the OS commands of tpm_clear -f or tpm_takeownership).  These actions didn't result in a physical presence detect request on reboot.

**Comment by benjamindoron** [comment]
> Tested https://github.com/benjamindoron/edk2_coreboot-dev/tree/upp_next and the TPM (1.2) isn't working on my Dell Tricky. I see the options in the setup screen but can't seem to take ownership or clear the TPM (either via the OS commands of tpm_clear -f or tpm_takeownership). These actions didn't result in a physical presence detect request on reboot.

I should have told you to apply https://review.coreboot.org/c/coreboot/+/45568 to coreboot master, but it wouldn't have helped in this case anyway. The physical presence library used by UefiPayload currently only exists for TPM 2.0. I tried to adapt the libraries for TPM 1.2, but it didn't work; I'll try to figure out where it fails.

> It appears there is some delay in bringing the TPM up from idle

The TCG PTP specification requires the TPM to go to idle after startup, and be returned to idle after each command. Either coreboot or FSP (or CSME!) don't do this, but for now I have a workaround for Tpm2DeviceLib that I'll push.

**Comment by benjamindoron** [comment]
I have an implementation of a SerialPortLib that logs to CBMEM working in QEMU. It's using a modification of the `FindCbTag` function from STM (which derives it from SeaBIOS).

I also have SeaBIOS working as CSM in QEMU, but this is more WIP. It can start a live CD (but doesn't login, perhaps QEMU is just slow). Support for the PAMs (legacy region) of various platforms has been added based on work contributed to OpenCore. Interrupts should/could work as well, but this would need testing. The BBS handover tables don't seem great either; TianoCore is starting SeaBIOS, which can then boot devices. Testing needs to be done on physical hardware, but SeaBIOS might require patches first.

I can elaborate more later. I will push patches when I rebase on the new tag (and hopefully get a chance to test on physical hardware as well).

**Comment by MrChromebox** [comment]
@benjamindoron very nice, looking forward to it

**Comment by benjamindoron** [comment]
That's up on https://github.com/benjamindoron/edk2_coreboot-dev/tree/upp_next. There's still some assert-related stuff to clean up. If coreboot does not advertise a serial port info table, BdsDxe asserts when UefiPayloadPkg's PlatformHookLib errors.

PlatformHookLibNull from MdeModulePkg should be used instead. I'll probably push patches over the weekend.

(But asserts aren't compiled into release builds, so it works anyways.)

**Pull request closed without merging**
