### PR TITLE
TPM1.2 updates

### PR DESCRIPTION
**Pull request by herve-elter**
@MrChromebox  Here are the changes I made to TPM 1.2 files to make it work with Coreboot & Edk2
Tested with Infineon SLB9660 & Atmel AT97SC3204

### CODE REVIEW

**Comment by MrChromebox** [comment]
With this PR, I now have TPM 1.2 controls in the settings menu, but they do not appear functional. Selecting any function from the menu (ie, disable and clear) just immediately returns to Device Manager. No change in status in menu.

**Comment by herve-elter** [comment]
After Reboot you should have the confirmations request

**Comment by herve-elter** [comment]
@MrChromebox compilation was done with this option -D VARIABLE_SUPPORT=SMMSTORE

**Comment by MrChromebox** [comment]
unfortunately not - it just reboots directly to the OS. Only time I get a confirmation request was after reboot when trying to reset it from Windows, but pressing F12 to confirm didn't seem to do anything, it just hung.

(side note: Will want to clear the screen before showing confirmation text, and have a different key to confirm since Chromebooks don't have F12)

**Comment by herve-elter** [comment]
Could you enable DEBUG and send me the log

**Comment by MrChromebox** [comment]
unfortunately I don't have serial output on these older ChromeOS devices.

If I disable/deactivate and reboot, then go to TPM menu --> still activated
If I disable/deactivate and reboot into Linux, reboot, then go to TPM menu --> now deactivated

**Comment by coolstar** [comment]
I may be able to get serial output from one of my old C720's in storage, will have to check if the Servo v2 still works

**Comment by herve-elter** [comment]
Just done a quick test this morning
Bios Menu TPM Operation -> Deactivate and Disable
Then Default Boot -> Bios message : Configuration changed. Reset to Apply it Now. Press ENTER to reset

Coreboot Log: Pending Request 0x07, OS Respond CMD 0x0 = 0x0
Edk2 Log: [TPM] Flags=1, PPRequest = 7
No prompt to apply TPM modification
Cold Reset
Coreboot Log: Pending Request 0x00, OS Respond CMD 0x7 = 0x0   (-> No execution error reported)
Edk2 Log: [TPM] Flags=1, PPRequest = 0
Enter Bios Setup and TPM Status is still Enable and not Deactivated :(

Test under Linux
echo 7 > /sys/class/tpm/tpm0/ppi/request
reboot
Same behavior 
Let's start debugging!

**Comment by herve-elter** [comment]
Adding more verbosity to coreboot gives me some interesting information!
After edk2 successfully disable and deactivate the TPM, the system performs a Cold reboot.
And I get this in the Coreboot log:

Found TPM SLB9660 TT 1.2 by Infineon
TPM: is disabled. Enabling...
TPM: Unexpected TPM deactivated state. Toggling...
TPM: setup succeeded

The problem seems to be in Coreboot and not in Edk2!

The same thing happens when you try to disable the TPM.
After a reboot coreboot enable it again 
Found TPM SLB9660 TT 1.2 by Infineon
TPM: is disabled. Enabling...
TPM: setup succeeded

**Comment by herve-elter** [comment]
@MrChromebox  I let you modify in coreboot file:/src/security/tpm/tspi/tspi.c  function tpm1_invoke_state_machine and remove unnecessary things...
Works now for me

**Comment by MrChromebox** [comment]
@herve-elter looking at tpm1_invoke_state_machine(), I think it can be skipped entirely - what do you think?

**Comment by herve-elter** [comment]
@MrChromebox Yes, mine only return TPM_SUCCESS ;

**Pull request merged**
